--Cria um script para inserir valores em uma tabela em loop

IF OBJECT_ID('TABELA_DE_NUMEROS', 'U') IS NOT NULL 
    DROP TABLE TABELA_DE_NUMEROS
IF OBJECT_ID('TABELA_DE_NUMEROS', 'U') IS NULL 
    CREATE TABLE TABELA_DE_NUMEROS (NUMERO INT, [STATUS] VARCHAR(20)); 

DECLARE @NUMERO_INICIAL_SEQUENCIA INT,
        @NUMERO_FINAL_SEQUENCIA INT,
        @NOTA_FISCAL_TESTE INT;

SET @NUMERO_INICIAL_SEQUENCIA = 1;
SET @NUMERO_FINAL_SEQUENCIA = 200;

WHILE @NUMERO_INICIAL_SEQUENCIA <= @NUMERO_FINAL_SEQUENCIA
BEGIN
    SELECT @NOTA_FISCAL_TESTE = COUNT(*) FROM NOTAS_FISCAIS WHERE NUMERO = @NUMERO_INICIAL_SEQUENCIA;
    IF @NOTA_FISCAL_TESTE = 1
        INSERT INTO TABELA_DE_NUMEROS (
            NUMERO, [STATUS]
            ) VALUES (
                @NUMERO_INICIAL_SEQUENCIA, 'É uma nota fiscal');
    ELSE
        INSERT INTO TABELA_DE_NUMEROS(
            NUMERO, [STATUS]
            ) VALUES (
                @NUMERO_INICIAL_SEQUENCIA, 'Não é uma nota fiscal');
    SET @NUMERO_INICIAL_SEQUENCIA = @NUMERO_INICIAL_SEQUENCIA + 1;
END;

SELECT * FROM TABELA_DE_NUMEROS

SELECT * FROM NOTAS_FISCAIS;


--Cria um script para inserir valores em uma tabela em loop de acordo com intervalo de tempo

IF OBJECT_ID('TABELA_DATA_NUMEROS', 'U') IS NOT NULL 
    DROP TABLE TABELA_DATA_NUMEROS
IF OBJECT_ID('TABELA_DATA_NUMEROS', 'U') IS NULL 
    CREATE TABLE TABELA_DATA_NUMEROS (DATA DATE, TOTAL_DE_NOTAS VARCHAR(20)); 

DECLARE @DATA_INICIAL DATE,
        @DATA_FINAL DATE,
        @TOTAL_NOTA INT;

SET @DATA_INICIAL = '2017-01-01';
SET @DATA_FINAL = '2017-01-10';

WHILE @DATA_INICIAL <= @DATA_FINAL
BEGIN
    SELECT @TOTAL_NOTA= COUNT(*) FROM NOTAS_FISCAIS WHERE DATA_VENDA = @DATA_INICIAL;
    INSERT INTO TABELA_DATA_NUMEROS(
            DATA, [TOTAL_DE_NOTAS]
            ) VALUES (
                @DATA_INICIAL, @TOTAL_NOTA);
    SET @DATA_INICIAL = DATEADD(DAY, 1, @DATA_INICIAL);
END;

SELECT * FROM TABELA_DATA_NUMEROS;