--Controle de Fluxo com IF
IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL DROP TABLE TABELA_TESTE;
IF OBJECT_ID('TABELA_TESTE', 'U') IS NULL CREATE TABLE TABELA_TESTE(ID VARCHAR (10));

--Controle do dia da semana
--Seleciona o dia de hoje
SELECT GETDATE();

--Seleciona o dia da semana
SELECT DATENAME(WEEKDAY,GETDATE());

--Adiciona dias
SELECT GETDATE(), DATEADD(DAY, 5, GETDATE());

--Seleciona o dia da semana daqui 5 dia a partir de hoje
SELECT DATENAME(WEEKDAY, DATEADD(DAY, 5, GETDATE()));

--Colocando as informações em variáveis
DECLARE @DIA_SEMANA VARCHAR(20),
        @NUMERO_DIAS INT;

SET @NUMERO_DIAS = 11;
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()));
PRINT(@DIA_SEMANA);

--Verifica se é fim de semana
IF @DIA_SEMANA = 'Domingo' OR @DIA_SEMANA = 'Sábado'
    PRINT('Esse dia é fim de semana');
ELSE
    PRINT('Esse dia é dia de semana');

--Desafio
DECLARE @CPF VARCHAR(15),
        @DATA_NASCIMENTO DATE,
        @IDADE_CLIENTE INT,
        @IDADE INT;

SET @CPF = '1471156710';
SELECT @DATA_NASCIMENTO = DATA_DE_NASCIMENTO FROM TABELA_DE_CLIENTES WHERE CPF = @CPF;
SELECT @IDADE_CLIENTE = IDADE FROM TABELA_DE_CLIENTES WHERE CPF = @CPF;
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());

IF @IDADE != @IDADE_CLIENTE
    UPDATE TABELA_DE_CLIENTES SET IDADE = @IDADE WHERE CPF = @CPF;


--Verifica limite de crédito
DECLARE @LIMITE_MAXIMO FLOAT,
        @BAIRRO VARCHAR(50);

SET @LIMITE_MAXIMO = 50000;
SET @BAIRRO = 'Agua Santa';

IF @LIMITE_MAXIMO <= (SELECT SUM(LIMITE_DE_CREDITO) FROM TABELA_DE_CLIENTES WHERE BAIRRO = @BAIRRO)
    PRINT 'O limite de crádito ultrapassou o máximo permitido';
ELSE
    PRINT 'O crédito está dentro do limite máximo permitido';

-- Desafio
DECLARE @CPF VARCHAR(15),
        @DATA_NASCIMENTO DATE,
        @IDADE INT;

SET @CPF = '1471156710';
SELECT @DATA_NASCIMENTO = DATA_DE_NASCIMENTO FROM TABELA_DE_CLIENTES WHERE CPF = @CPF;
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());

IF @IDADE != (SELECT IDADE FROM TABELA_DE_CLIENTES WHERE CPF = @CPF)
    UPDATE TABELA_DE_CLIENTES SET IDADE = @IDADE WHERE CPF = @CPF;