--Listando nome dos clientes e CPF
DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;
SELECT @NUMERO_CLIENTES = COUNT(*) FROM TABELA_DE_CLIENTES;
SET @I = 1;
WHILE @I <= @NUMERO_CLIENTES
BEGIN
        SELECT @CPF = X.CPF, @NOME = X.NOME
        FROM ( SELECT Row_Number() Over (Order By CPF) as RowNum, * FROM TABELA_DE_CLIENTES) X
        WHERE X.RowNum = @I;
        PRINT @CPF + ' - ' + @NOME;
        SET @I = @I + 1;
END;

--Incluindo valor de venda na listagem de clientes do mês 01/2015
DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;
DECLARE @MES INT, @ANO INT;
DECLARE @TOTAL_VENDAS FLOAT;

SET @MES = 1;
SET @ANO = 2015;
SELECT @NUMERO_CLIENTES = COUNT(*) FROM TABELA_DE_CLIENTES;
SET @I = 1;
WHILE @I <= @NUMERO_CLIENTES
BEGIN
        SELECT @CPF = X.CPF, @NOME = X.NOME
        FROM ( SELECT Row_Number() Over (Order By CPF) as RowNum, * FROM [TABELA_DE_CLIENTES]) X
        WHERE X.RowNum = @I;

        SELECT @TOTAL_VENDAS = SUM(INF.QUANTIDADE * INF.PRECO)
        FROM NOTAS_FISCAIS NF
        INNER JOIN ITENS_NOTAS_FISCAIS INF
        ON NF.NUMERO = INF.NUMERO
        WHERE NF.CPF = @CPF
        AND YEAR(NF.DATA_VENDA) = @ANO AND MONTH(NF.DATA_VENDA) = @MES;
        PRINT 'Vendas para ' + @CPF + ' - ' + @NOME + ' NO MÊS ' + CONVERT(VARCHAR(2), @MES) + ' E ANO ' + TRIM(STR(@ANO, 15, 2)) + ' FOI DE ' + CONVERT(VARCHAR(20), @TOTAL_VENDAS);
        SET @I = @I + 1;
END;

--Guardando o resultado da listagem de clientes em um tabela temporária
DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;
DECLARE @MES INT, @ANO INT;
DECLARE @TOTAL_VENDAS FLOAT;
DECLARE @TABELA_FINAL TABLE (CPF VARCHAR(11), NOME VARCHAR(100), MES INT, ANO INT, TOTAL_VENDAS FLOAT) 

SET @MES = 1;
SET @ANO = 2015;
SELECT @NUMERO_CLIENTES = COUNT(*) FROM TABELA_DE_CLIENTES;
SET @I = 1;
WHILE @I <= @NUMERO_CLIENTES
BEGIN
        SELECT @CPF = X.CPF, @NOME = X.NOME
        FROM ( SELECT Row_Number() Over (Order By CPF) as RowNum, * FROM [TABELA_DE_CLIENTES]) X
        WHERE X.RowNum = @I;

        SELECT @TOTAL_VENDAS = SUM(INF.QUANTIDADE * INF.PRECO)
        FROM NOTAS_FISCAIS NF
        INNER JOIN ITENS_NOTAS_FISCAIS INF
        ON NF.NUMERO = INF.NUMERO
        WHERE NF.CPF = @CPF
        AND YEAR(NF.DATA_VENDA) = @ANO AND MONTH(NF.DATA_VENDA) = @MES;
        INSERT INTO @TABELA_FINAL VALUES (
            @CPF, @NOME, @MES, @ANO, @TOTAL_VENDAS
        );
        PRINT 'Vendas para ' + @CPF + ' - ' + @NOME + ' NO MÊS ' + CONVERT(VARCHAR(2), @MES) + ' E ANO ' + TRIM(STR(@ANO, 15, 2)) + ' FOI DE ' + CONVERT(VARCHAR(20), @TOTAL_VENDAS);
        SET @I = @I + 1;
END;
SELECT * FROM @TABELA_FINAL;


--Listando código e nome do produto

DECLARE @CODIGO VARCHAR(10),
        @PRODUTO VARCHAR(50),
        @NUM_PRODUTO INT,
        @CONTADOR INT;
SET @CONTADOR = 1;
SELECT @NUM_PRODUTO = COUNT(*) FROM TABELA_DE_PRODUTOS;

WHILE @CONTADOR >= @NUM_PRODUTO
BEGIN
    SELECT @CODIGO = X.CODIGO_DO_PRODUTO, @PRODUTO = X.NOME_DO_PRODUTO
    FROM (SELECT Row_Number() Over (Order by CODIGO_DO_PRODUTO) AS RowNum, * FROM TABELA_DE_PRODUTOS) X
    WHERE X.RowNum = @CONTADOR;
    PRINT '-' + @CODIGO + '-' + @PRODUTO;
    SET @CONTADOR = @CONTADOR + 1;
END;

--Desafio: incluir total de produtos vendidos no mês 01/2015
DECLARE @CODIGO VARCHAR(10),
        @PRODUTO VARCHAR(50),
        @NUM_PRODUTO INT,
        @CONTADOR INT;
DECLARE @MES INT;
DECLARE @ANO INT;
DECLARE @TOTAL_VENDAS FLOAT;

SET @CONTADOR = 1;
SET @MES = 1;
SET @ANO = 2015;
SELECT @NUM_PRODUTO = COUNT(*) FROM TABELA_DE_PRODUTOS;

WHILE @CONTADOR >= @NUM_PRODUTO
BEGIN
    SELECT @CODIGO = X.CODIGO_DO_PRODUTO, @PRODUTO = X.NOME_DO_PRODUTO
    FROM (SELECT Row_Number() Over (Order by CODIGO_DO_PRODUTO) AS RowNum, * FROM TABELA_DE_PRODUTOS) X
    WHERE X.RowNum = @CONTADOR;
    SELECT @TOTAL_VENDAS = SUM(INF.QUANTIDADE * INF.PRECO)
    FROM NOTAS_FISCAIS NF
    INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON NF.NUMERO = INF.NUMERO
    WHERE INF.CODIGO_DO_PRODUTO = @CODIGO AND YEAR(NF.DATA_VENDA) = @ANO AND MONTH(NF.DATA_VENDA) = @MES;
    PRINT 'Vendas do produto: ' + @CODIGO + '-' + @PRODUTO + 'no mês' + CONVERT(varchar(2), @MES) + 'do ano' + 
        CONVERT(VARCHAR(4), @ANO) + 'totalizou' + TRIM(STR(@TOTAL_VENDAS, 15, 2));
    SET @CONTADOR = @CONTADOR + 1;
END;


